# Generated by Django 3.1.2 on 2020-10-21 19:09

from django.db import migrations, models
import django.db.models.deletion


def seedDb(apps, schema_editor):
    DocumentType = apps.get_model("SIM_CRUD", "DocumentType")
    DocumentType(name="Cédula de Ciudadanía", code="CC").save()
    DocumentType(name="Tarjeta de Identidad", code="TI").save()
    DocumentType(name="Cedula Extranjería", code="CE").save()
    DocumentType(name="Número Único de Identificación Personal",
                 code="NUIP").save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('code', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField()),
                ('runt_registry', models.TextField()),
                ('exam', models.BooleanField()),
                ('documentTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIM_CRUD.documenttype')),
            ],
        ),
        migrations.RunPython(seedDb),
    ]
